CREATE TABLE PERSONS
(
    NAME           VARCHAR(250),
    SURNAME        VARCHAR(250),
    AGE            INT,
    PHONE_NUMBER   INT,
    CITY_OF_LIVING VARCHAR(250),
    PRIMARY KEY (NAME,SURNAME,AGE)
);

SELECT NAME, SURNAME
FROM PERSONS T
WHERE T.CITY_OF_LIVING = 'MOSCOW';

SELECT *
FROM PERSONS T
WHERE T.AGE > 27
ORDER BY T.AGE DESC;

INSERT INTO PERSONS (NAME, SURNAME, AGE)
VALUES ('PETR', 'IVANOV', 27);

INSERT INTO PERSONS (NAME, SURNAME, AGE)
VALUES ('IVAN', 'PETROV', 22);

INSERT INTO PERSONS (NAME, SURNAME, AGE)
VALUES ('MICHA', 'SINYAK', 43);

INSERT INTO PERSONS (NAME, SURNAME, AGE, CITY_OF_LIVING)
VALUES ('OLEG', 'PUSHKIN', 35, 'MOSCOW');

